#!/usr/bin/php
<?php declare(strict_types = 1);

require __DIR__ . '/app_init.php';
/** @var  \Pimple\Container $container */

$application = new \Symfony\Component\Console\Application();

$application->add(new \Middle\Skeleton\Command\ExampleCommand());

$application->run();
